function aa(b,e,f,n,h){function r(){try{if(!y||0==y.length)return"";for(var a=y.length,c=Math.max.apply(null,y),d=Math.min.apply(null,y),g=0,m=0;m<a;m++)g+=y[m];return"&dvp_numts="+a+"&dvp_maxts="+c+"&dvp_mints="+d+"&dvp_avgts="+Math.round(g/a)}catch(b){return""}}function l(a,c){x=x.replace(ca[a],"&dbg"+a+"="+c)}function w(a,c){if(a instanceof Array){for(var d=0,g=a.length;d<g;d++)a[d]=a[d]+"="+c;return"&"+a.join("&")}return"&"+a+"="+c}var p=new J,t=h&&h.dvObj||window.$dv,k=h&&"undefined"!==typeof h.billable||
t&&t.tags[$uid]&&t.tags[$uid].billable,c=h&&h.impressionId||window.$uid,g=window.Zf||n,d=Array(g.mb),a=g.ab/g.ic+1,m=null,q="";b=b?b:null;f=f?f:"";var v="",C=null,D=0,Q=void 0,y=void 0,U=new RegExp(/&strp=[^&]*/),z=new RegExp(/&narme=[^&]*/),da=new RegExp(/&narm=[^&]*/),ea=new RegExp(/&naral=[^&]*/),fa=new RegExp(/&evid=[^&]*/);n=new RegExp(/&jsver=[^&]*/);for(var ga=new RegExp(/&vct=[^&]*/),ca=[new RegExp(/&dbg0=[^&]*/),new RegExp(/&dbg1=[^&]*/),new RegExp(/&dbg2=[^&]*/),new RegExp(/&dbg3=[^&]*/),
new RegExp(/&dbg4=[^&]*/),new RegExp(/&dbg5=[^&]*/),new RegExp(/&dbg6=[^&]*/),new RegExp(/&dbg7=[^&]*/),new RegExp(/&dbg8=[^&]*/),new RegExp(/&dbg9=[^&]*/),new RegExp(/&dbg10=[^&]*/),new RegExp(/&dbgtx=[^&]*/)],ha=[new RegExp(/&b0=[^&]*/),new RegExp(/&b1=[^&]*/),new RegExp(/&b2=[^&]*/),new RegExp(/&b3=[^&]*/),new RegExp(/&b4=[^&]*/),new RegExp(/&b5=[^&]*/),new RegExp(/&b6=[^&]*/),new RegExp(/&b7=[^&]*/),new RegExp(/&b8=[^&]*/),new RegExp(/&b9=[^&]*/),new RegExp(/&b10=[^&]*/),new RegExp(/&b11=[^&]*/)],
Y=Array(g.mb),u={ga:{G:null,H:null,A:null,v:null,Te:!1},j:{u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,Te:!1},za:{Eb:null,Db:null},Lb:0},K="",L="",F,G,M="",N="",O=!1,H="",V=0;V<g.mb;V++)Y[V]="&b"+V+"=";e=function(a,c){if(a&&c)return c.replace(new RegExp(a+"=\\d*[&^#]"),"")}("prndr",e?e:null);var I=f+"?"+e,I=n.test(I)?I.replace(n,"&jsver="+b):I+"&jsver="+b,x="&naral=&narm=&narme=&dbg2=&dbg3=&dbg4=&dbg5=&dbg6=&dbg7=&dbg8=&dbg9=&dbg10=&dbgtx=&vct=",A="&strp=";e="&ctime="+(new Date).getTime();
var P=0,R="",S="",T=0,B=0,E=0,W=0;this.Yc=function(){return P};this.Pc=I+A+x+e+v+K;setEventId=function(a){C=a;x=x.replace(fa,"&evid="+C)};setAdLocatorIndicator=function(a){T=T|a;x=x.replace(ea,"&naral="+T)};setNAPMeasure=function(a){p.a("l2("+a+")");B=B|a;ia()?(setNotApplicableTime(),P=0):0==P&&(P=(new Date).getTime());x=x.replace(da,"&narm="+B);p.a("l2e")};setNAPMeasureErr=function(a){E=E|a;x=x.replace(z,"&narme="+E)};this.yd=function(a){W=W|a;x=x.replace(ga,"&vct="+W)};setBuckectStr=function(a,
c){c?v=v.replace(ha[a],"&b"+a+"="+d[a]):v=v+"&b"+a+"="+d[a]};setNotApplicableTime=function(){0!=P&&(R=(new Date).getTime()-P)};getBucketString=function(){return v};getFraudNonFraudEvents=function(a,c,d){return O?w(c,d):w(a,d)};this.rc=function(){return O};this.xd=function(a){m=a;A=A.replace(U,"&strp="+m);this.xd=function(){}};this.qb=function(){return(new Date).getTime()};var ja=this.qb();this.Ee=function(){return ja};this.Ff=function(){O=!0};this.Df=function(a,c){H+="&"+c.reportQueryString.viewrate+
"="+a[c.serverProperties.viewedRate]+"&"+c.reportQueryString.error+"="+a[c.serverProperties.error]+"&"+c.reportQueryString.projected+"="+(1==a[c.serverProperties.viewed]?2:a[c.serverProperties.projected]);if("undefined"===typeof a[c.serverProperties.featurebit]||a[c.serverProperties.featurebit]&&1==a[c.serverProperties.featurebit])H+="&"+c.reportQueryString.measurems+"=0",1==a[c.serverProperties.viewed]&&(H+="&"+c.reportQueryString.viewedms+"=0")};this.qf=function(){B=B&-3;E=E&-2;E&=-3};this.Gb=function(){setNAPMeasure(2)};
this.Bf=function(){setNAPMeasureErr(8);this.xc()};this.xc=function(){setNAPMeasure(4)};this.td=function(){setAdLocatorIndicator(8);this.Gb()};this.Ed=function(a){setAdLocatorIndicator(16);l(9,a)};this.Fd=function(){setAdLocatorIndicator(1)};this.zf=function(){this.Gb();setNAPMeasureErr(1)};this.yf=function(){this.Gb();setNAPMeasureErr(2)};this.wc=function(a,c){setNAPMeasure(8);S=p.Wc(a,c)};this.vf=function(){p.a("l1");B=B&-3;setNAPMeasure(1);p.a("l1e")};this.wd=function(){setNAPMeasure(16)};this.ve=
function(){return d};this.ud=function(m,b){c=c||h&&h.impressionId||window.$uid;var q;try{c&&t&&t.tags[c]&&t.tags[c].getTimeDiff&&(q=t.tags[c].getTimeDiff())}catch(k){}var f=q-Q||100;Q=q;y?200>y.length&&y.push(f):y=[];p.a("ie15");0<=m.i&&(q=Math.floor(m.i/g.ic),0<m.i%g.ic?q++:0<m.i&&q++,isNaN(d[q])&&(d[q]=0),d[q]+=Math.max(b,f),m.N&&q>=a||0==m.N&&6<=q?D+=Math.max(b,f):timeStampTotalBuckets=D=0);p.a("ie15e")};this.Ge=function(){for(var a=0,c=0;c<d.length;c++)d[c]&&(a+=d[c]);return a};this.xf=function(a){var c=
O?"false":a.gd;a="&advisonl="+(null==a.gd?"":c)+("&adabvvponl="+(null==a.fd?"":a.fd));l(8,"CSS1Compat"===document.compatMode?1:0);p.a("ff52");void 0!=document.documentMode&&null!=document.documentMode&&l(10,document.documentMode);p.a("ff52e");K=a};this.eb=function(a){p.a("ie14");N="&adbtftopg="+(null==a?"":O?"true":a)};this.wf=function(a){null!=a&&(u=a)};this.vd=function(a){p.a("ie19");this.wf(a.I);this.Ef();p.a("ie19e")};this.Id=function(){var a;a="&vptoscrx="+(null!=u.ga.G?Math.round(u.ga.G):"");
a+="&vptoscry="+(null!=u.ga.H?Math.round(u.ga.H):"");a+="&vpwdth="+(null!=u.ga.A?Math.round(u.ga.A):"");a+="&vphgt="+(null!=u.ga.v?Math.round(u.ga.v):"");a+="&adtovpx="+(null!=u.j.u?Math.round(u.j.u):"");a+="&adtovpy="+(null!=u.j.s?Math.round(u.j.s):"");a+="&adtopgx="+(null!=u.j.J?Math.round(u.j.J):"");a+="&adtopgy="+(null!=u.j.K?Math.round(u.j.K):"");a+="&adtoscrx="+(null!=u.j.C?Math.round(u.j.C):"");a+="&adtoscry="+(null!=u.j.D?Math.round(u.j.D):"");a+="&scrwdth="+(null!=u.za.Eb?Math.round(u.za.Eb):
"");a+="&scrhgt="+(null!=u.za.Db?Math.round(u.za.Db):"");return a+="&almesind="+u.Lb};this.Jd=function(){var a="";if(F&&G){var c=null!=u.j.o?u.j.o:null,d=null!=u.j.m?u.j.m:null;0>F*G&&(a+="&dvp_adwdth="+F,a+="&dvp_adhgt="+G,F=c,G=d)}else F=null!=u.j.o?u.j.o:null,G=null!=u.j.m?u.j.m:null;a+="&adwdth="+(null!=F?F:"");return a+="&adhgt="+(null!=G?G:"")};this.Ef=function(){setNotApplicableTime();v="";for(var a=0;a<d.length;a++)d[a]&&(v+=Y[a]+d[a]);L=this.Jd();M=K+this.Id()+L;M+=N;this.Pc=I+A+x+v+M};this.Vc=
function(){return 1E3<=D};this.ea=function(a){c=c||h&&h.impressionId||window.$uid;var d=I+"&impid="+c,g=-1,m=p.tb();try{t&&t.tags[c]&&t.tags[c].getTimeDiff&&(g=t.tags[c].getTimeDiff())}catch(b){}switch(a){case 1:q=g;d+=A+x+"&napt="+R+M+m+"&napr="+S;m="";k&&(m=h.$a?getFraudNonFraudEvents(["isbmms"],"isfbmms",g):getFraudNonFraudEvents(["isbmms","isgmmims"],"isfbmms",g));d+=m+getFraudNonFraudEvents("ismms","isfmms",g)+"&isumms="+g;break;case 2:d+=A+x+"&napt="+R+M+m+"&napr="+S+getFraudNonFraudEvents("isnmms",
"isfnmms",g);break;case 3:d+="&istoms="+g;case 4:case 8:d+=A+N+L+"&isbxdms="+g+(O?"&fbxdtb="+this.Ge():v)+r();break;case 5:q=q||g;d+=A+N+L+K+getFraudNonFraudEvents("isiabvms","isfiabvms",g)+"&isuiabvms="+g+getFraudNonFraudEvents("ismms","isfmms",q)+"&isumms="+q+r();break;case 6:q=q||g;d+=N+L+K+getFraudNonFraudEvents("iscvmvms","isfcvmvms",g)+getFraudNonFraudEvents("ismms","isfmms",q)+r();break;case 16:d+=A+x+"&napt="+R+m+"&napr="+S+"&ishems="+g;break;case 7:return d;case 9:d+=H;break;case 10:d+="&ismms=0";
break;case 17:q=q||g;m=h.$a?["isbmms"]:["isbmms","isgmmims"];d+=A+N+L+K+getFraudNonFraudEvents(h.$a?["isbvms"]:["isbvms","isgmpims"],"isfbvms",g)+getFraudNonFraudEvents(m,"isfbmms",q);break;default:d=this.Pc+"&napt="+R+"&ctime="+this.qb()+m+"&napr="+S}return d+"&evid="+a+"&ctime="+this.qb()};this.ue=function(){p.a("ie17");for(var a=[],c=0;c<g.mb;c++)a[c]=d[c]?d[c]:0;return a};var ia=this.ac=function(){return 2==(B&2)&&8!=(T&8)||4==(B&4)||8==(E&8)&&8==(T&8)?!1:!0};this.kf=function(a){p.a("l3");a=p.da(a);
p.a("cm3e");a&&(l(5,a.w),l(6,a.h));p.a("l3e")};return this}
function ba(b,e){this.window=null;this.ob={};this.images={};this.Jb=this.T=function(b){navigator.sendBeacon(b,{})};this.window=b;"function"!=typeof navigator.sendBeacon&&(this.dc=function(b){var e=this.window.document.createElement("img");e.name=e.id=b;e.width=0;e.height=0;e.style.display="none";e.src="";this.window.document.body.insertBefore(e,this.window.document.body.firstChild);return e},this.Jb=function(b,e){if(e&&1!=this.ob[e]||16==e)this.images[e]?(this.images[e].src=b,this.ob[e]=1):this.T(b,
e)},this.T=function(b,e){if(e&&1!=this.ob[e]||16==e||7==e)this.window.document.createElement("img").src=b,this.ob[e]=1},this.window&&(this.images={3:this.dc(e+"_13"),4:this.dc(e+"_14"),8:this.dc(e+"_18")}));return this}function X(){this.Jb=function(){};this.T=function(){}}
function ka(b,e,f,n){function h(){if(1==v){try{for(var a in m)q.removeChild(m[a]);d.document.body.removeChild(q)}catch(c){}v=!1}}function r(a){a=a||0;var c=p(0);c.ld()?7<c.sb()?(h(),D=C=v=!1):(v=!0,C=!1):20>a?(a++,setTimeout(r,50,a)):(v=C=D=!1,h())}function l(a){$dv&&$dv.tags&&$dv.tags[n]&&$dv.tags[n].getTimeDiff&&$dv.tags[n].getTimeDiff();if(null!==a.jb)for(var c=0;c<a.jb.length;c++){var d=p(c).sb();0==c?d>Q&&(Q=d):d>y&&(y=d)}}function w(a){for(var c=!0,d=0;13>=d;d++)var g=p(d),c=c&(null!==g&&g.ld());
if(!c)return null;a.Kc=0;a.uc=0;a.tc=0;a.pc=0;a.Ea=0;a.jb=Array(13);c=p(0).sb();for(d=1;13>=d;d++)if(g=5<Math.abs(p(d).sb()-c),a.jb[d]=g)switch(a.Kc++,d){case 2:case 3:case 4:case 5:a.uc++;break;case 6:case 7:case 8:case 9:a.tc++;break;case 10:case 11:case 12:case 13:a.pc++}if(13===a.Kc)return a.Ea=100,l(a),!0;c=a.jb;if(!1===c[1]){if(3<=a.pc||3<=a.tc||3<=a.uc)return l(a),null;a.Ea=0;l(a);return!1}if(!0===c[1]&&(!0===c[2]&&!0===c[3]||!0===c[2]&&!0===c[4]||!0===c[3]&&!0===c[5]||!0===c[4]&&!0===c[5])||
!0===c[1]&&4==a.tc||!0===c[1]&&4==a.pc&&1<=a.uc)return a.Ea=50,l(a),!0;if(c[2]&&c[5]&&!(c[6]&&c[10]&&c[1]&&c[13]&&c[9])||c[4]&&c[3]&&!(c[8]&&c[12]&&c[1]&&c[11]&&c[7]))return l(a),null;a.Ea=0;l(a);return!1}function p(a){a=m[a];var c=null;a&&(c=a.contentWindow);return c}function t(){for(var d=a.getBoundingClientRect(),g=d.width,b=d.height,q=g/(1+c),k=b/(1+c),e=g/c,t=b/c,v=0;13>=v;v++){var f=d.left,h=d.top;switch(v){case 0:h=f=-1E5;break;case 1:f+=(g-1)/2;h+=(b-1)/2;break;case 3:f+=g-1;break;case 4:h+=
b-1;break;case 5:f+=g-1;h+=b-1;break;case 6:f+=(g-e)/2;h+=(b-t)/2;break;case 7:f+=(g-e)/2+e;h+=(b-t)/2;break;case 8:f+=(g-e)/2;h+=(b-t)/2+t;break;case 9:f+=(g-e)/2+e;h+=(b-t)/2+t;break;case 10:f+=(g-q)/2;h+=(b-k)/2;break;case 11:f+=(g-q)/2+q;h+=(b-k)/2;break;case 12:f+=(g-q)/2;h+=(b-k)/2+k;break;case 13:f+=(g-q)/2+q,h+=(b-k)/2+k}6<=v&&(f-=.5,h-=.5);var l=m[v];l.style.left=f+"px";l.style.top=h+"px"}}function k(){if(null!=a&&null!=a.parentNode){C=!0;q=d.document.createElement("div");d.document.body.appendChild(q);
for(var c=0;13>=c;c++){var g=d.document.createElement("iframe");g.width=1;g.height=1;g.style.position="absolute";g.frameBorder="0";g.style.visibility="hidden";g.style.zIndex=-9999999;g.style.display="block";g.src="javascript:no=false;yes=true;("+function(){window.af={ee:100};window.Sc=no;window.hb=0;window.Tc=0;window.ed=0;window.$f=no;window.sb=function(){return window.ed};window.ld=function(){return window.Sc};window.Ze=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||
window.msRequestAnimationFrame;window.$b=function(){window.hb++;window.Ze(window.$b,document)};window.$b();setInterval(function(){10>window.hb&&window.$b();window.ed=window.hb-window.Tc;window.Tc=window.hb},window.af.ee);window.setTimeout(function(){window.Sc=yes},250)}.toString()+")();";q.appendChild(g);m.push(g)}t()}}var c=Math.sqrt(2),g=new J,d=null,a=null,m=[],q,v=!1,C=!1,D=g.zb(b,e,f),Q=0,y=0;this.Pe=function(){0==C&&(0==(this.Za()&&(null!=a&&g.kd(a,d)?!0:!1))?v=!1:(k(),r()))};this.Za=function(){return D};
this.We=function(){return v};this.zd=function(c,g){d=c;a=g;this.Pe()};this.Ie=function(){if(0==v)return null;var a={};return null==w(a)?null:a.Ea}}
function la(b,e,f,n,h,r,l,w){this.b=new J;this.window=b;this.f=e;this.S=f;this.L=n;this.Z=l&&l.Enums.BrowserId||window.$dv.Enums.BrowserId;this.ba=l&&l.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario;this.O=h;this.oc=r;this.ia=null;this.dd=this.window?this.b.Ab(this.window.top):this.b.Ab(window.top);this.Se=this.S!=this.ba.CrossDomain&&this.b.Va("ofs")&&this.dd;this.ia=new ka(this.S,this.L,l,w);null!=this.ia&&this.ia.Za()&&this.ia.zd(this.window,this.f);this.vb=this.Bb=this.ta=null;this.wb=
!1;var p=0;this.ka={Vd:1,Wd:2,Pd:4,Rb:8,Od:16,Sb:32,Ud:64};this.vc=function(b,k,c,g){if(g&&g.insertBefore&&g.firstChild&&(b=this.window.document.createElement(b))){for(var d in k)b[d]=k[d];for(d in c)b.style[d]=c[d];g.insertBefore(b,g.firstChild);return b}return null};this.se=function(b,k,c){var g=this.window.top,d=b.width,a=b.height;0>c.left?(d=b.width-Math.abs(c.left),0>k.Da&&(d-=Math.abs(k.Da))):0>k.Da&&(d=b.width-Math.abs(k.Da)+c.left,d=d>b.width?b.width:d);var m=b.width,q=Math.min(this.b.Ba(g.window).clientWidth,
g.innerWidth),e=screen.availWidth-q-k.Da,f=0;d<m?(m=d,f=q-d,0>k.Da&&(f-=Math.abs(k.Da))):f=q-m-c.left;0>f?(d=m-Math.abs(f),0>e&&(d-=Math.abs(e))):0>e&&(d=m-Math.abs(e)+f,d=d>m?m:d);k=screen.availHeight-k.rf-g.outerHeight;g=Math.min(this.b.Ba(g.window).clientHeight,g.innerHeight)-b.height-c.top;0>g?(a=b.height-Math.abs(g),0>k&&(a-=Math.abs(k))):0>k&&(a=b.height-Math.abs(k)+g,a=a>b.height?b.height:a);0>c.top&&(a-=Math.abs(c.top));return{Mf:d,Nf:a}};this.kc=function(b,k,c,g){var d=c.A,a=c.v,m=0;c=0;
var q={width:k.right-k.left,height:k.bottom-k.top};if(0>k.bottom||0>k.right||k.top>a||k.left>d||0>=q.width||0>=q.height)return 0;0>k.top?Math.abs(k.top)>=q.height?m=q.height:(m=q.height+k.top,m>a&&(m=a)):m=k.top+q.height>a?a-k.top:q.height;0>k.left?Math.abs(k.left)>=q.width?c=q.width:(c=q.width+k.left,c>d&&(c=d)):c=k.left+q.width>d?d-k.left:q.width;this.Se&&(b=this.se(q,b,k),c=b.Mf,m=b.Nf);return 0>=c||0>=m?0:Math.round(c*m/(q.width*q.height)*(g?q.width*q.height/((g.right-g.left)*(g.bottom-g.top)):
1)*100)};this.jc=function(b,k){try{var c={x:b.offsetLeft,y:b.offsetTop};if(b.offsetParent){var g=this.jc(b.offsetParent,k);c.x+=g.x;c.y+=g.y}else k!=k.parent&&this.b.Tb(k,k.parent)&&(g=this.jc(k.frameElement,k.parent),c.x+=g.x,c.y+=g.y);return c}catch(d){return{x:null,y:null}}};this.qa=function(b){if(this.S==this.ba.CrossDomain)if(this.b.xa(this.window)&&this.window.$sf.ext.geom)this.qa=function(){var a=this.b.Ma(this.window),c=window.outerHeight||this.window.document.documentElement.clientHeight?
this.window.outerHeight-parseInt(a.win.h):this.O.Explorer.aa,d={A:null,v:null,G:null,H:null,g:!1};d.A=parseInt(a.win.w);d.v=parseInt(a.win.h);d.G=parseInt(a.win.l);d.H=parseInt(a.win.t)+c;d.g=!0;return d};else if(this.L.Y==this.Z.Firefox)this.qa=function(){var a=8==screen.top-this.window.screenY&&8==screen.left-this.window.screenX,c=a?0:this.window.screenX-screen.left,a=a?0:this.window.screenY-screen.top,d={A:null,v:null,G:null,H:null,g:!1};d.A=this.window.outerWidth;d.v=this.window.outerHeight-this.O.Firefox.aa;
d.G=c;d.H=a+this.O.Firefox.aa;d.g=!0;return d};else if(this.b.qc(this.window)){var k=this;this.window.context.observeIntersection(function(a){a.forEach(function(a){k.ta=a})});this.qa=function(){var a={A:null,v:null,g:!1,G:null,H:null};null!=this.ta?(a.A=this.ta.rootBounds.width,a.v=this.ta.rootBounds.height):(a.A=0,a.v=0);a.g=!0;return a}}else if(this.L.Y==this.Z.IE&&/^[11|12]/.test(this.L.wa))this.qa=function(){var a=-8==this.window.screenY&&-8==this.window.screenX,c=a?0:this.window.screenX,a=a?
0:this.window.screenY,d={A:null,v:null,G:null,H:null,g:!1};d.A=this.window.outerWidth;d.v=this.window.outerHeight-this.O.Explorer.aa;d.G=c;d.H=a+this.O.Explorer.aa;d.g=!0;return d};else if(this.L.Y==this.Z.IE&&/[6-9]|[10]/.test(this.L.wa)){var c=this.vc("iframe",{name:"dv_ie9onload",src:"",width:0,height:0,ne:0,bf:"0",cf:"0"},{display:"inline",position:"absolute",top:0,left:0,Lf:"none",zIndex:0,border:0},this.window.document.body),g=this.vc("iframe",{name:"dv_ie9onmousemove",src:"",width:0,height:0,
ne:0,bf:"0",cf:"0"},{display:"inline",position:"absolute",top:0,left:0,Lf:"none",zIndex:0,border:0},this.window.document.body),d=g.contentWindow||g.window||g.contentDocument.window||g.contentWindow.window||this.window.Qf,a=c.contentDocument||c.contentWindow.document,c=g.contentDocument||g.contentWindow.document,m="<html><head><script >window.onload = "+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.Ua={Wb:window.event.clientY,Vb:window.event.clientX,Hd:window.event.screenY-
window.event.clientY-window.screenY})}.toString()+"; \x3c/script></head><body></body></html>",g='<html><head></head><body><script > function runMoM(){ window.document.body.fireEvent("onmousemove");} window.document.body.onmousemove = '+function(a){a&&(window.event=a);isFinite(String(window.event.clientY))&&(parent.ua={Wb:window.event.clientY,Vb:window.event.clientX,Ha:window.event.screenY-window.event.y,Ga:window.event.screenX-window.event.x})}.toString()+"; runMoM();\x3c/script></body></html>";c.open("text/html",
"replace");c.write(g);c.close();a.open("text/html","replace");a.write(m);a.close();("CSS1Compat"===document.compatMode?this.window.document.documentElement:this.window.document.body).clientLeft;this.qa=function(){d.runMoM();a.open("text/html","replace");a.write(m);a.close();var c=this.window.ua,g=this.window.Ua,b=screen.availWidth,k=screen.availHeight,g=g?g.Hd:this.O.Explorer.aa;if(c){var e=c.Ga,f=c.Ha;c.Ga>=b&&(c.Ga-=b);c.Ha>=k&&(c.Ha-=k);var h={A:null,v:null,G:null,H:null,g:!1};h.A=this.window.outerWidth?
this.window.outerWidth-20:b-c.Ga-20;h.v=this.window.outerHeight?this.window.outerHeight-g-10:k-c.Ha-10;h.G=e;h.H=f;h.g=!0}else h={A:null,v:null,G:null,H:null,g:!1},h.A=this.window.outerWidth?this.window.outerWidth-20:b-20,h.v=this.window.outerHeight?this.window.outerHeight-g-10:k-10,h.G=null,h.H=null,h.g=!1;return h}}else this.b.yb()?(this.rd(),this.qa=function(){this.wb||this.rd();var a={A:null,v:null,G:null,H:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.O.Chrome.aa;a.g=
!1;return a}):this.qa=this.L.Y==this.Z.Chrome?function(){var a={A:null,v:null,G:null,H:null,g:!1},c=!1;try{a.A=this.window.frameElement.offsetParent.parentNode.clientWidth,a.v=this.window.frameElement.offsetParent.parentNode.clientHeight,c=!0}catch(d){}a.G=this.window.screenX;a.H=this.window.screenY;a.g=c;return a}:null!=this.ia&&this.ia.Za()?function(){var a={A:null,v:null,G:null,H:null,g:!1};a.A=this.window.outerWidth;a.v=this.window.outerHeight-this.O.Safari.aa;a.g=!1;return a}:function(){return{A:null,
v:null,G:null,H:null,g:!1}};else this.qa=function(){var a,c,d=this.window.top;void 0!=d.mozInnerScreenX&&null!=d.mozInnerScreenX?(a=d.mozInnerScreenX,c=d.mozInnerScreenY):void 0!=d.screenX&&null!=d.screenX?0!=d.screenLeft+8&&d.screenLeft+8!=screen.width||0!=d.screenTop+8&&d.screenTop+8!=screen.height?(a=d.screenLeft,c=d.screenTop+(d.outerHeight-d.innerHeight)):(a=d.screenLeft+8,c=d.screenTop+(d.outerHeight-d.innerHeight)+8):(a=d.screenLeft,c=d.screenTop);var g={A:null,v:null,G:null,H:null,g:!1},b=
this.b.Ba(d);g.A=d.innerWidth||b.clientWidth;g.v=d.innerHeight||b.clientHeight;g.G=a;g.H=c;g.g=!0;return g};return this.qa(b)};this.oa=function(b,k){p=1;this.S==this.ba.CrossDomain?this.b.xa(this.window)&&this.window.$sf.ext.geom&&this.b.Ma(this.window).par?(p=8,this.oa=function(){var c=this.b.Ma(this.window),g=window.outerHeight||this.window.document.documentElement.clientHeight?this.window.outerHeight-parseInt(c.win.h):this.O.Explorer.aa,d={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,
g:!1,rect:null,P:null,sa:null};d.u=parseInt(c.self.l)-parseInt(c.par.l);d.s=parseInt(c.self.t)-parseInt(c.par.t);d.J=parseInt(c.self.l);d.K=parseInt(c.self.t);d.C=parseInt(c.win.l)+d.u;d.D=parseInt(c.win.t)+d.s+g;d.o=parseInt(c.self.w);d.m=parseInt(c.self.h);d.g=!0;d.rect={top:d.s,bottom:d.s+d.m,left:d.u,right:d.u+d.o};return d}):this.L.Y==this.Z.Firefox?this.oa=function(){var c=1;window.devicePixelRatio&&(c=window.devicePixelRatio);var g=this.window.screenX,d=this.window.screenY,a=this.window.mozInnerScreenX/
c-g,c=this.window.mozInnerScreenY/c-d-this.O.Firefox.aa,a={left:a,top:c,right:a+this.window.innerWidth,bottom:c+this.window.innerHeight},c={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};c.u=a.left;c.s=a.top;c.J=null;c.K=null;c.C=g+a.left;c.D=d+a.top;c.o=this.window.innerWidth;c.m=this.window.innerHeight;c.g=!0;c.rect=a;this.b.Kb()&&(c=this.pb(c));return c}:this.b.qc(this.window)?(p=32,this.oa=function(){var c={u:null,s:null,o:null,m:null,g:!1,rect:null,P:null,
sa:null,J:null,K:null,C:null,D:null};null!=this.ta?(c.u=this.ta.boundingClientRect.left,c.s=this.ta.boundingClientRect.top,c.o=this.ta.boundingClientRect.width,c.m=this.ta.boundingClientRect.height):(c.u=0,c.s=0,c.o=0,c.m=0);c.g=!0;c.rect={top:c.s,bottom:c.s+c.m,left:c.u,right:c.u+c.o};return c}):this.L.Y==this.Z.IE&&/^[11|12]/.test(this.L.wa)?this.oa=function(c){var g=this.window.screenLeft-window.screenX,d=this.window.screenTop-window.screenY-this.O.Explorer.aa,g={left:g,top:d,right:g+this.window.innerWidth,
bottom:d+this.window.innerHeight},d={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};d.u=g.left;d.s=g.top;d.J=null;d.K=null;d.C=c.G+g.left;d.D=c.H+g.top;d.o=this.window.innerWidth;d.m=this.window.innerHeight;d.g=!0;d.rect=g;this.b.Kb()&&(d=this.pb(d));return d}:this.L.Y==this.Z.IE&&/[6-9]|[10]/.test(this.L.wa)?this.oa=function(){if(8==document.documentMode)return{u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};var c=this.window.Ua&&
this.window.ua?this.window.Ua.Wb-this.window.ua.Wb:0,g=this.window.Ua&&this.window.ua?this.window.Ua.Vb-this.window.ua.Vb:0,d=this.b.Ba(this.window),a={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};a.u=g;a.s=c;a.J=null;a.K=null;a.C=this.window.ua?g+this.window.ua.Ga:null;a.D=this.window.ua?c+this.window.ua.Ha:null;a.o=this.window.innerWidth||d.clientWidth;a.m=this.window.innerHeight||d.clientHeight;a.g=!0;a.rect={left:g,top:c,right:g+(this.window.innerWidth||
d.clientWidth),bottom:c+(this.window.innerHeight||d.clientHeight)};this.b.Kb()&&(a=this.pb(a));return a}:this.b.yb()?(p=512,this.oa=function(){var c={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};null!=this.f&&(adData=this.b.rb(this.f),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}):this.oa=this.L.Y==this.Z.Chrome?function(){var c=null,g=null,d=!1;try{var a=this.window.frameElement.offsetTop,c=this.window.frameElement.offsetLeft-
this.window.frameElement.offsetParent.scrollLeft,g=a-this.window.frameElement.offsetParent.scrollTop,d=!0}catch(b){}a={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};a.u=c;a.s=g;a.J=null;a.K=null;a.C=null;a.D=null;a.o=this.window.innerWidth;a.m=this.window.innerHeight;a.g=d;a.rect=d?{left:c,top:g,right:c+this.window.innerWidth,bottom:g+this.window.innerHeight}:null;this.b.Kb()&&(a=this.pb(a));return a}:null!=this.ia&&this.ia.Za()?function(){var c={u:null,s:null,
J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null};null!=this.f&&(adData=this.b.rb(this.f),c.o=adData?adData.w:this.window.innerWidth,c.m=adData?adData.h:this.window.innerHeight);return c}:function(){return{u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null}}:this.oa=function(c){var g=this.jc(this.f,this.window),d={u:null,s:null,J:null,K:null,C:null,D:null,o:null,m:null,g:!1,rect:null,P:null,sa:null},a=this.b.lc(this.f,this.window),b=this.b.Dc(this.f,
this.window);d.u=b.left;d.s=b.top;d.J=g.x;d.K=g.y;d.C=c.G+b.left;d.D=c.H+b.top;d.o=b.w;d.m=b.h;d.g=!0;d.rect=a;d.P=b;return d};return this.oa(b,k)};this.pb=function(b){if(this.window.document.body==this.f||this.window.document.documentElement==this.f)return b;var k=this.b.rb(this.f);if(k){var c=k.w,g=k.h,d=b.u,a=b.s,m=b.D,e=b.C;null!=b.u&&null!=b.s&&null!=b.m&&null!=b.o&&b.rect&&(0<k.t?(a=b.s+k.t,null!=b.D&&(m=b.D+k.t)):g+=k.t,0<k.l?(d+=k.l,null!=b.C&&(e=b.C+k.l)):c+=k.l,k.r>b.o&&(c-=k.r-b.o),k.Jc>
b.m&&(g-=k.Jc-b.m),b.o=0<c?c:0,b.m=0<g?g:0,b.u=d,b.s=a,b.D=m,b.C=e,b.rect.left=b.u,b.rect.top=b.s,b.rect.right=b.u+k.w,b.rect.bottom=b.s+k.h,b.P={w:c,h:g,left:d,right:d+c,top:a,bottom:a+g})}return b};this.De=function(){var b=screen.availWidth,k=screen.availHeight,c=screen.width,g=screen.height,d=0,a=0;this.dd&&(a=this.window.top,d=a.screenX,a=a.screenY);return{g:$dv.CommonData&&$dv.CommonData.deviceType&&1==$dv.CommonData.deviceType?"undefined"!==typeof d:!1,Eb:b||c,Db:k||g,Xf:d,Yf:a,Da:d-(c-b),rf:a-
(g-k)}};this.qe=function(){var b=this.De(),k=this.qa(b),c=this.oa(k,b);return{ga:k,j:c,za:b,Lb:(null==k.G||null==k.H?0:this.ka.Vd)|(null==k.A||null==k.v?0:this.ka.Wd)|(null==c.u||null==c.s?0:this.ka.Pd)|(null==c.J||null==c.K?0:this.ka.Rb)|(null==c.C||null==c.D?0:this.ka.Od)|(null==c.m||null==c.o?0:this.ka.Sb)|(null==b.Db||null==b.Eb?0:this.ka.Ud),N:this.Oc(c.m,c.o)}};this.Oc=function(b,k){null==b&&(b=0);null==k&&(k=0);return this.O.Gf&&242500<=b*k?!0:!1};this.ye=function(){this.b.a("c10");if(null!=
this.f)if(this.b.kd(this.f,this.window))try{var b={timeStamp:new Date,i:-3,la:-3,I:null,N:!1,ha:0};if(!this.oc())return b;var k=this.qe();if(!k.j.g||!k.ga.g){if(this.b.xa(this.window)&&this.window.$sf.ext.inViewPercentage){var c=this.window.$sf.ext.inViewPercentage();return{timeStamp:new Date,i:c,la:c,I:k,N:k.N,ha:16}}if(this.b.yb()&&this.wb)return c=0,null!=this.vb&&(c=Math.round(100*this.vb.intersectionRatio)),{timeStamp:new Date,i:c,la:c,I:k,N:this.Oc(k.j.m,k.j.o),ha:512};if(this.ia.Za()){var g=
{timeStamp:new Date,i:-3,la:-3,I:null,N:!1,ha:2};if(0==this.ia.We())g.i=-6,g.la=-6,this.ia.zd(this.window,this.f);else{var d=this.ia.Ie();null!=d&&(g.I=k,g.N=k.N,g.i=d,g.la=d)}return g}b.I=k;p&&(b.ha=p);return b}if(k.j&&k.j.P&&(0===k.j.P.w||1===k.j.P.w||0===k.j.P.h||1===k.j.P.h))return{timeStamp:new Date,i:-5,la:-5,I:k,ha:p};c=k.j.P?this.kc(k.za,k.j.P,k.ga,k.j.rect):this.kc(k.za,k.j.rect,k.ga);return{timeStamp:new Date,i:c,la:c,I:k,N:k.N,ha:p}}catch(a){return{timeStamp:new Date,i:-4,la:-4,I:null,
N:!1,ha:p}}else return{timeStamp:new Date,i:-2,la:-2,I:null,N:!1,ha:0};else return{timeStamp:new Date,i:-1,la:-1,I:null,N:!1,ha:0}};this.re=function(b,k){this.b.a("c11");var c=null,g=null;if(null!=b.I){var d=b.I.j;k<=this.O.ff&&(c=0<=b.i||-5==b.i?b.N&&b.i>=this.O.ab||0==b.N&&50<=b.i?!0:!1:null,g=b.N?this.O.ab/100:.5,g=0==c?0>d.s+d.m*g?!0:!1:1==c?!1:null)}return{fd:g,gd:c}};this.xb=function(b){this.b.a("c12");var k=null;if(2!=b.ha&&512!=b.ha&&null!=b.I){var c=b.I.Lb,g=b.I.j;(c&this.ka.Rb)==this.ka.Rb&&
(c&this.ka.Sb)==this.ka.Sb&&(k=this.kc(b.I.za,{left:g.J,top:g.K,right:g.J+g.o,bottom:g.K+g.m},b.I.ga,g.rect),k=0<=b.i?b.N&&k>=this.O.ab||0==b.N&&50<=k?!1:!0:null)}this.b.a("c12e");return k};this.rd=function(){function b(c){c.forEach(function(c){k.vb=c})}var k=this;"undefined"!=typeof IntersectionObserver&&null!=this.f&&(p=512,this.Bb=new IntersectionObserver(b,{threshold:[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1]}),this.Bb.observe(this.f),this.wb=!0)};this.Oe=function(){this.f=null;null!=this.Bb&&(this.Bb.disconnect(),
this.vb=null,this.wb=!1)}}
function J(){this.getElementVolume_object=function(b){var e=b.getAttribute("width"),f=b.getAttribute("height");null==e||""==e||null==f||""==f?(b=b.parentNode,b={w:b.clientWidth,h:b.clientHeight}):b={w:e,h:f};return b};this.Xe=function(b){var e=0;try{for(;null!=b&&10>e;){if("none"==window.getComputedStyle(b).display||"hidden"==window.getComputedStyle(b).visibility)return!1;b=b.parentElement;e++}}catch(f){}return!0};this.da=function(b,e){this.a("cm1");var f=null,n=b.nodeName.toLowerCase();e&&this["getElementVolume_"+
n]&&(f=this["getElementVolume_"+n](b));if(!f&&(f=this.rb(b),this.a("cm2e"),!f||1>=f.w||1>=f.h))return this.a("cm1e"),{w:0,h:0};f.w.indexOf&&f.w.indexOf("px")&&(f.w=f.w.replace("px",""));f.h.indexOf&&f.h.indexOf("px")&&(f.h=f.h.replace("px",""));this.a("cm1e");return f};this.rb=function(b){this.a("cm2");try{var e;return document.body.getBoundingClientRect&&(e=b.getBoundingClientRect())?{w:e.right-e.left,h:e.bottom-e.top,l:e.left,t:e.top,Jc:e.bottom,r:e.right}:null}catch(f){return null}};this.Ba=function(b){this.a("ff8");
b=b.document.documentElement.clientHeight?b.document.documentElement:b.document.body;this.a("ff8e");return b};this.Xc=function(b,e){this.a("ff9");var f=0,n=!1;if(b.document.all)for(var h=0;h<b.document.all.length;h++)"BODY"==b.document.all[h].nodeName&&(n=!0),n&&("width"==e?b.document.all[h].width>f&&(f=b.document.all[h].width):b.document.all[h].height>f&&(f=b.document.all[h].height));this.a("ff9e");return f};this.nd=function(b,e){for(var f=this.Ba(b),n=b.innerWidth||f.clientWidth||this.Xc(b,"width"),
f=b.innerHeight||f.clientHeight||this.Xc(b,"height"),h=e.length,r=0,l=0;l<h;l++)if(15>=Math.abs(n-e[l].w)){r=e[l].h.length;for(n=0;n<r;n++)if(15>=Math.abs(f-e[l].h[n]))return!0;break}return!1};this.Hf=function(b){for(var e=[],f=-1;e[++f]=b[f];);e.length--;return e};this.Ob=function(b,e,f,n){var h=b.getElementsByTagName("*"),h=this.Hf(h);h.unshift(b);for(var r=["EMBED","IFRAME","OBJECT","IMG","DIV"],l=[],w=0;w<h.length;w++){var p=h[w];if(-1!=r.indexOf(p.nodeName)){var t=n(p);t&&l.push({Ic:t.w*t.h,
w:t.w,h:t.h,type:p.nodeName||"other",me:p})}}l=l.sort(function(b,c){return c.Ic-b.Ic||r.indexOf(c.type)-r.indexOf(b.type)});(e=0<l.length&&l[0].w>e&&l[0].h>f?l[0].me:null)&&b&&(e.ub=b.ub);return e};this.kd=function(b,e){this.a("ff10");try{if(!b)return!1;for(e||(e=window);b!=e.document&&b.parentNode;)b=b.parentNode;this.a("ff10e");return b==e.document}catch(f){return!1}};this.lc=function(b,e){var f=e.parent,n={left:0,right:0,top:0,bottom:0};if(b){var h=b.getBoundingClientRect();e!=f&&this.Tb(e,f)&&
(n=this.lc(e.frameElement,f));n={left:h.left+n.left,right:h.right+n.left,top:h.top+n.top,bottom:h.bottom+n.top}}return n};this.Tb=function(b,e){var f=!1;if(b==e)f=!0;else try{b.document.domain==e.document.domain&&(f=!0)}catch(n){}return f};this.ze=function(b){if(b)try{if(b.contentDocument&&this.jd(b.contentDocument))return b.contentDocument;if(b.contentWindow&&this.Ab(b.contentWindow))return b.contentWindow.document}catch(e){}return null};this.ad=function(b){return b?b.defaultView||b.parentWindow:
null};this.Re=function(b,e){return-1<e.indexOf(b)};this.te=function(b){try{return b!=b.top&&b.parent&&this.Ab(b.parent)?b.parent:null}catch(e){return null}};this.Ab=function(b){try{return b&&b.document&&this.jd(b.document)?!0:!1}catch(e){return!1}};this.jd=function(b){try{return b&&b.getElementsByTagName&&b.getElementById?!0:!1}catch(e){return!1}};this.Dc=function(b,e){var f=e.parent,n={w:0,h:0,left:0,right:0,top:0,bottom:0};b&&(n=this.lc(b,e),n.w=n.right-n.left,n.h=n.bottom-n.top,e!=f&&this.Tb(e,
f)&&(f=this.Dc(e.frameElement,f),f.bottom<n.bottom&&(f.bottom<n.top&&(n.top=f.bottom),n.bottom=f.bottom),f.top>n.top&&(f.top>n.bottom&&(n.bottom=f.top),n.top=f.top),f.right<n.right&&(f.right<n.left&&(n.left=f.right),n.right=f.right),f.left>n.left&&(f.left>n.right&&(n.right=f.left),n.left=f.left),n.w=n.right-n.left,n.h=n.bottom-n.top));return n};this.cc=function(b,e){return function(){return b.apply(e,arguments)}};this.pa=function(b){try{return b?b.length?b.length:0:0}catch(e){return 0}};this.nc=function(b){for(var e=
[],f=0;f<b.length;f++)this.Xe(b[f])&&e.push(b[f]);return e};this.a=function(b){try{maxLength=3,$dv&&($dv.Na=$dv.Na||[],$dv.Na.push(b),$dv.Na.length>maxLength&&$dv.Na.shift())}catch(e){}};this.tb=function(){try{return $dv&&$dv.Na?"&dvp_log="+$dv.Na.join():""}catch(b){return""}};this.xa=function(b){if(b.$sf&&b.$sf.ext)if(b.$sf.ext.geom){if(b=this.Ma(b),null!=b&&b.win&&(0<b.win.h||0<b.win.w))return this.xa=function(){return!0},!0}else if(b.$sf.ext.inViewPercentage)return!0;this.xa=function(){return!1};
return!1};this.Ma=function(b){b.$sf.ext.geom&&(this.Ma="function"==typeof b.$sf.ext.geom?function(b){return b.$sf.ext.geom()}:function(b){return b.$sf.ext.geom});return this.Ma(b)};this.qc=function(b){return b.context&&b.context.observeIntersection?!0:!1};this.yb=function(){var b=!1;if(1==this.Va("disableIO"))return!1;"undefined"!=typeof IntersectionObserver&&(b=!0);return b};this.zb=function(b,e,f){var n=f&&f.Enums.BrowserId||window.$dv.Enums.BrowserId;if(b==(f&&f.Enums.TrafficScenario||window.$dv.Enums.TrafficScenario).CrossDomain&&
e.Y===n.Safari&&(null===e.wa||void 0===e.wa||!/^[3-8]/.test(e.wa)))return this.zb=function(){return!0},!0;this.zb=function(){return!1};return!1};this.Va=function(b){var e,f=this.Uc();f&&f.AVO&&(e=f.AVO[b]);return e};this.Uc=function(){var b={},e=window.$dv,f=window.$uid;e.tags&&e.tags[f]&&(b=e.tags[f]);return b};this.Kb=function(){return 1==this.Va("sam")?!0:!1};this.Xa=function(b){return b.document.hasFocus()};this.La=new function(){var b=this;b.cache=[];window.addEventListener?b.add=function(e,
f,n,h,r){if("undefined"==typeof h||null==h)h=window;h.addEventListener(e,f,n);r&&b.cache.push([e,f,n,h])}:window.attachEvent?b.add=function(e,f,n,h,r){if("undefined"==typeof h||null==h)h=window;h["e"+e+f]=f;h[e+f]=function(){h["e"+e+f](window.event)};h.attachEvent("on"+e,h[e+f]);r&&b.cache.push([e,f,n,h])}:b.add=function(){};window.removeEventListener?b.remove=function(b,f,n,h){if("undefined"==typeof h||null==h)h=window;h.removeEventListener(b,f,n)}:window.detachEvent?b.remove=function(b,f,n,h){if("undefined"==
typeof h||null==h)h=window;h.detachEvent("on"+b,h[b+f]);h[b+f]=null;h["e"+b+f]=null}:b.remove=function(){};b.flush=function(){for(var e=0;e<b.cache.length;e++)b.remove.apply(b,b.cache[e]);b.cache=[]}};this.Wc=function(b,e){var f=b||"",n="";if(e&&(f+=": "+(e.message||""),e.stack)){var n=e.stack||"",h=n.indexOf("at ");0>h&&(h=0);n=", Stack: "+n.slice(h,n.length)}f=f.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,"");n=n.replace(/\n/g,"").replace(/\r/g,"").replace(/\t/g,"").replace(/\|/g,
"").replace(/    at/g,"at").replace(/\?/g,"-").replace(/&/g,"-");h=null;try{h=encodeURIComponent(f+n).slice(0,500)}catch(r){try{h=encodeURIComponent(f).slice(0,500)}catch(l){h=f.slice(0,500)}}return h}}
function ma(b,e,f,n,h){function r(c,b){for(var d=[],a=0;a<p.length;a++){var m=[],m=b(c,p[a]),k=l.pa(m);if(0!=k){var f=l.ad(p[a]);if(null!=f)for(var e=0;e<k;e++)try{m[e].ub=f,d.push(m[e])}catch(h){}}}return d}var l=new J,w="Microsoft Internet Explorer"==navigator.appName;this.c=n;this.window=f;this.Mb=[["DCF",'"'],[";",";"],["%3B","%3B"],["zoneid=","_"],["zoneid%3D","_"],["PRImpID=",""],["PRImpID%3D",""],["PRPID=",""],["PRPID%3D",""]];this.Cb=[1==w?"object":"embed",1==w?"embed":"object","href","img",
"span","iframe","frameElement","div"];this.Hb=this.f=null;this.dataObj=b;this.dvObj=b.dvObj||window.$dv;this.L={Y:this.dvObj.CommonData.BrowserId,wa:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.S=h;this.ba=this.dvObj.Enums.TrafficScenario;this.he=function(){var c=this.dataObj.ec+"-"+this.dataObj.bc;this.dataObj.isBrandShieldOrigin&&(c+="-bs");return c.replace(RegExp(",","g"),";")};this.yc=this.he();this.W=e;this.B={F:{h:1,w:1},Of:{h:10,w:10},df:10};115==this.dataObj.Yb&&
(this.B.F.h=20,this.B.F.w=20);this.dataObj.findclass&&1==this.dataObj.findclass&&this.Cb.push("classDeclaration");this.dataObj.lb&&0<this.dataObj.lb.length&&this.Cb.unshift("searchCustomElementsFromTag");this.searchByAdSrvId_8=function(c,b){l.a("a1");var d=/[0-9]+-[0-9]+-[0-9]+-[0-9]+/.exec(c);return null!=d&&(d=d.toString(),d.replace(RegExp("-","g"),"")==b)?!0:!1};this.fc=this["searchByAdSrvId_"+(this.dataObj?this.dataObj.Yb||"":"")];this.getElementsByClassName=function(c,b){return r(c,function(c,
a){l.a("ff1");var m=a.getElementsByClassName(c);l.a("ff1e");return"1"!=b?m:l.nc(m)})};this.querySelectorAll=function(c,b){return r(c,function(c,a){l.a("ff3");var m=a.querySelectorAll("."+c);l.a("ff3e");return"1"!=b?m:l.nc(m)})};this.getElementsByTagName=function(c,b){return r(c,function(c,a){l.a("ff4");var m=a.getElementsByTagName(c);l.a("ff4e");return"1"!=b?m:l.nc(m)})};this.classDeclaration=function(){l.a("a9");var c="undefined"!==typeof window.document.getElementsByClassName,b="undefined"!==typeof window.document.querySelectorAll;
if(!(1>this.dataObj.M.length)){var d=[];if(c)d=this.getElementsByClassName(this.dataObj.M,this.dataObj.displaynon);else if(b)d=this.querySelectorAll(this.dataObj.M,this.dataObj.displaynon);else return;c=l.pa(d);for(b=0;b<c;b++)if(d[b]&&!this.ra(d[b])){var a=l.da(d[b]);if(a&&a.h>this.B.F.h&&a.w>this.B.F.w&&this.V(d[b])){this.f=d[b];break}}}};this.searchCustomElementsFromTag=function(){for(var c=0;c<this.dataObj.lb.length&&(this.Qc(this.dataObj.lb[c]),!this.f);c++);};this.Qc=function(c){if(!(1>this.dataObj.M.length)){c=
this.getElementsByTagName(c,this.dataObj.displaynon);for(var b=l.pa(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d],!0)&&!this.ra(c[d])){var a=l.da(c[d]);if(a&&a.h>this.B.F.h&&a.w>this.B.F.w&&this.V(c[d])){this.f=c[d];break}var m=l.Ob(c[d],this.B.F.w,this.B.F.h,l.cc(l.da,l));if(m&&this.V(m)){this.f=m;this.V(c[d]);break}if((m=this.hd(c[d]))&&(a=l.da(m))&&a.h>this.B.F.h&&a.w>this.B.F.w&&this.V(m)){this.f=m;this.V(c[d]);break}}}};this.div=function(){this.Qc("div")};this.span=function(){l.a("a10");
if(!(1>this.dataObj.M.length))for(var c=this.getElementsByTagName("span",this.dataObj.displaynon),b=l.pa(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d],!0)&&!this.ra(c[d])){if(this.Qe(c[d])){this.f=c[d];break}var a=l.Ob(c[d],this.B.F.w,this.B.F.h,l.cc(l.da,l));if(a&&this.V(a)){this.f=a;this.V(c[d]);break}if(a=this.hd(c[d])){var m=l.da(a);if(m&&m.h>this.B.F.h&&m.w>this.B.F.w&&this.V(a)){this.f=a;this.V(c[d]);break}}}};this.object=function(){l.a("a11");for(var c=this.getElementsByTagName("object",
this.dataObj.displaynon),b=l.pa(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&!this.ra(c[d])){var a=l.Ob(c[d],this.B.F.w,this.B.F.h,l.cc(l.da,l));if(a&&this.V(a)){this.V(c[d]);this.f=a;break}}};this.embed=function(){l.a("a12");for(var c=this.getElementsByTagName("embed",this.dataObj.displaynon),b=l.pa(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&!this.ra(c[d])){var a=l.da(c[d]);if(a&&a.h>this.B.F.h&&a.w>this.B.F.w&&this.V(c[d])){this.f=c[d];break}}};this.href=function(){l.a("a13");for(var c=
this.getElementsByTagName("a",this.dataObj.displaynon),b=l.pa(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&!this.ra(c[d])){var a=c[d].getElementsByTagName("img");if(0<a.length){var m=l.da(a[0]);if(m&&m.h>this.B.F.h&&m.w>this.B.F.w&&this.V(c[d])){this.f=a[0];break}}}};this.img=function(){l.a("a14");for(var c=this.getElementsByTagName("img",this.dataObj.displaynon),b=l.pa(c),d=0;d<b;d++)if(c[d]&&this.Aa(this.dataObj,c[d])&&0>c[d].src.indexOf("event")&&!this.ra(c[d])){var a=l.da(c[d]);if(a&&a.h>
this.B.F.h&&a.w>this.B.F.w&&this.V(c[d])){this.f=c[d];break}}};this.iframe=function(){l.a("a15");for(var c=this.getElementsByTagName("iframe",this.dataObj.displaynon),b=l.pa(c),d=0;d<b&&!this.Gc(c[d]);d++);};this.frameElement=function(){try{l.a("a16"),this.S==this.ba.SameDomain&&this.Gc(this.window.frameElement)}catch(c){}};this.Gc=function(c){l.a("a17");return this.Aa(this.dataObj,c)?this.Xd(c):!1};this.V=function(c){l.a("a18");if(c&&0==this.ra(c))try{var b=c.getAttribute("dvvisit");b?c.setAttribute("dvvisit",
b+","+this.yc):(l.a("ff5"),b=this.window.document.createAttribute("dvvisit"),l.a("ff5e"),b.value=this.yc,c.setAttributeNode(b));return!0}catch(d){}return!1};this.jf=function(c){c&&c.hasAttribute&&c.hasAttribute("dvvisit")&&c.removeAttribute("dvvisit")};this.pf=function(){this.jf(this.f);this.f=null};this.ra=function(c){l.a("a19");if(c&&(c=c.getAttribute("dvvisit"))){c=c.split(",");for(var b=0;b<c.length;b++)if(c[b]==this.yc)return!0}return!1};this.Qe=function(c){l.a("a20");return c&&"1"==c.getAttribute("adunit")?
!0:!1};this.hd=function(c){var b=null;if("celtra-ad-v3"==c.className)this.Ya=!0,c.celtra&&1==c.celtra.loaded&&(b=c.celtra.viewabilityObservee);else{c=c.getElementsByClassName("celtra-ad-v3");for(var d=l.pa(c),a=0;a<d;a++){this.Ya=!0;var m=c[a];if(m&&m.celtra&&1==m.celtra.loaded){b=m.celtra.viewabilityObservee;break}}}b&&(b.ub=l.ad(b.ownerDocument)||this.window);return b};this.Xd=function(c){l.a("a21");if(c&&!this.ra(c)){var b=l.da(c);if(b&&b.h>this.B.F.h&&b.w>this.B.F.w&&this.V(c))return this.f=c,
!0}return!1};this.Aa=function(c,b,d){l.a("a22");var a=null;return c.M&&0<c.M.length&&(this.Ec=1==c.Ye?this.Ld:this.Pb,a=this.Rd(c,b,d))||!this.f&&(a=this.Sd(c,b))?!0:!1};this.Rd=function(c,b,d){l.a("a23");var a;try{if(c.Nc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(a=this.ma(b.id,c.M))||(a=this.ma(b.src,c.M));a||(a=this.ma(b.href,c.M));a||(a=this.ma(b.getAttribute("flashvars"),c.M));a||(a=this.ma(b.name,c.M));!a&&this.dataObj.findclass&&1==this.dataObj.findclass&&(a=this.ma(b.getAttribute("class"),
c.M));if(!a&&this.dataObj.Ja&&0<this.dataObj.Ja.length)for(var m=this.dataObj.Ja,k=0;k<m.length&&!(a=this.ma(b.getAttribute(m[k]),c.M));k++);a||d||(a=this.ma(b.innerHTML,c.M));a&&!d&&(a=this.Qd(c,b));return a}catch(f){return a}};this.Sd=function(c,b){l.a("a24");var d;try{if(c.Nc&&b&&b.hasAttribute&&b.hasAttribute("dv-view"))return!0;(d=this.Fa(b.id,c))||(d=this.Fa(b.src,c));d||(d=this.Fa(b.href,c));d||(d=this.Fa(b.Tf,c));d||(d=this.Fa(b.name,c));d||(d=this.Fa(b.innerHTML,c));if(!d&&this.dataObj.Ja&&
0<this.dataObj.Ja.length)for(var a=this.dataObj.Ja,m=0;m<a.length&&!(d=this.ma(b.getAttribute(a[m]),c.M));m++);return d}catch(k){return d}};this.Fa=function(c,b){l.a("a25");if(!c)return!1;c=c.toLowerCase();for(var d=0;d<this.Mb.length;d++){var a;if(b.Hc&&(a=(this.Mb[d][0]+b.Hc).toLowerCase(),a=c.indexOf(a),-1<a)||b.pd&&(a=(this.Mb[d][0]+b.pd).toLowerCase(),a=c.indexOf(a),-1<a))return!0}return!1};this.Qd=function(c,b){l.a("a26");return null==c.kb||""==c.kb?!1:this.ma(this.Kd(b),c.kb)};this.Kd=function(c){l.a("a27");
if(c.outerHTML)return c.outerHTML;for(var b=c.attributes.length,d="",a=0;a<b;a++)d=d+c.attributes[a].nodeName+"="+c.attributes[a].nodeValue+" ";return d+c.innerHTML};this.ma=function(c,b){l.a("a28");return!c||!b||5>b.length?!1:null!=(this.Ec?this.Ec(c,b):this.Pb(c,b))?!0:this.fc&&"function"===typeof this.fc?this.fc(c,b):!1};this.Ld=function(c,b){l.a("a29");var d;try{d=(new RegExp(b)).exec(c)}catch(a){d=this.Pb(c,b)}return d};this.Pb=function(c,b){l.a("a30");var d=null;-1!==c.indexOf(b)&&(d=c);return d};
this.oe=function(c){l.a("a31");if(this.Be())return this.c.Fd(),this.Ya||(this.Ya=!0),this.f;if(this.dataObj.M&&0<this.dataObj.M.length&&!0===this.Ya&&1<c)return this.f;"1"!=this.dataObj.displaynon&&(c=this.Ce())&&c.node&&(this.c.Ed(c.Ka),this.f=c.node);return this.f};var p=[];this.Be=function(){l.a("32");if(this.dataObj.M&&0<this.dataObj.M.length){var c=this.Cb.length,b=this.window,d=0,a=[];try{do{a.push(b.document);for(var m=a,k=b.document.getElementsByTagName("iframe")||[],f=0;f<k.length||25>f;f++){var e=
null,e=l.ze(k[f]);void 0!==e&&null!==e&&0==l.Re(e,m)&&m.push(e)}b=l.te(b)}while(b&&10>++d)}catch(h){}p=a;for(b=0;b<c;b++)if(this[this.Cb[b]](),this.f){this.Hb=this.f;break}}return this.f};var t=[],k=["object","embed","img","iframe"];this.dataObj.spotXmode&&(k=["object","embed","video","iframe"]);this.Ue=function(c){l.a("a33");c=l.da(c);return this.Ve(c)};this.Ve=function(c){if(c){var b=c.w;c=c.h;for(var d=e.length,a=0,m=0;m<d;m++)if(15>=Math.abs(b-e[m].w))for(var a=e[m].h.length,k=0;k<a;k++)if(15>=
Math.abs(c-e[m].h[k]))return!0}return!1};this.we=function(){l.a("a34");return this.xe()||this.sf()};this.sf=function(){l.a("a35");var c=(window.name||(window.frameElement?window.frameElement.id:"")).substr(7),b=[],d=window.parent;l.a("ff6");try{b=d.document.getElementsByTagName("script")}catch(m){}l.a("ff6e");for(var d=b.length,a=0;a<d;a++)if(b[a]&&b[a].id&&b[a].id.substr(7)==c)return b[a];return null};this.xe=function(){l.a("a36");return this.dvObj&&this.dataObj.impressionId&&this.dvObj.tags&&this.dvObj.tags[this.dataObj.impressionId]?
this.dvObj.tags[this.dataObj.impressionId].tagElement:null};this.Ce=function(){l.a("a37");var c=this.we(),b=null;c&&(b=this.be(c));return b};this.be=function(c){l.a("a38");var b={node:c,Ka:0};c=[];for(t=[];b||0<c.length;){try{var d;a:{var a=b.node;try{if(a&&-1!=k.indexOf(a.nodeName.toLowerCase())){d=!0;break a}}catch(f){}d=!1}if(d&&this.Ue(b.node)&&!this.ra(b.node)&&this.V(b.node))return b;if(b.Ka<=this.B.df){var m,e=b.node,h=b.Ka,b=[],n=e.parentNode;n&&-1==t.indexOf(n)&&(t.push(n),b.push({node:n,
Ka:h+1}));if(e.hasChildNodes())for(var p=0;p<e.childNodes.length;p++)e.childNodes[p]&&-1==t.indexOf(e.childNodes[p])&&1===e.childNodes[p].nodeType&&(t.push(e.childNodes[p]),b.push({node:e.childNodes[p],Ka:h+1}));var r,w=e,U=[],z=null;w&&w.parentNode&&(z=w.parentNode.firstChild);for(;z;)1===z.nodeType&&z!==w&&U.push(z),z=z.nextElementSibling||z.nextSibling;r=U;for(p=0;p<r.length;p++)r[p]&&-1==t.indexOf(r[p])&&1===r[p].nodeType&&(t.push(r[p]),b.push({node:r[p],Ka:h+1}));if(m=b)for(b=0;b<m.length;b++)c.push(m[b])}}catch(f){}b=
c.shift()}return{node:null}};return this}
function dv_CustomClientViewAssureService(b){function e(b){return{settings:b.settings,buckets:0,reported:!1,eventId:b.eventId,Qa:b.Qa,nb:b.nb}}this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this.b=new J;var f=[],n=null,h=null,r=null,l=null;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&(n=this.dvObj.tags[this.impressionId].cvmSettings,h=this.dvObj.tags[this.impressionId].billable,r=this.dvObj.tags[this.impressionId].bprjct,l=this.dvObj.tags[this.impressionId].gmmod);
this.Bc=window.dv_cvmSettings||n||b.cvmSettings;this.Zb=window.dv_billable||h||b.billable;this.Mc=window.Vf||r||b.bprjct;this.bd=window.Wf||l;this.ie=new e({settings:this.Bc,eventId:6,Qa:["CustomViewabilityViewable"]});var w=this.b.Va("rpv"),n=this.b.Uc().bgm;b.$a=1==w&&1==n;this.Lc=new e({settings:this.Zb,eventId:17,Qa:b.$a?["BillableViewedImpression"]:["BillableViewedImpression","GroupMPassedImpression"],nb:!0});this.Bc&&f.push(this.ie);this.Zb&&f.push(this.Lc);b.na=b.na||[];n={serverProperties:{projected:"bp",
viewed:"bpv",viewedRate:"bpvr",error:"bperr"},reportQueryString:{projected:"isbprjct",measurems:"isbmms",viewedms:"isbvms",viewrate:"prjctbvr",error:"prjctber"}};this.Mc&&(n={serverData:this.Mc,projectionData:n,reportRTN:!0},b.na.push(n));n={serverProperties:{projected:"gmp",viewed:"gmpv",viewedRate:"gmpvr",error:"gmperr"},reportQueryString:{projected:"isgmmod",measurems:"isgmmims",viewedms:"isgmpims",viewrate:"modgmvr",error:"modgmer"}};this.bd&&(n={serverData:this.bd,projectionData:n,reportRTN:!0},
b.na.push(n));this.ae=dv_InViewService;this.ae(b);var p=this.Qb;this.Qb=function(b){b=p(b);for(var c=0;c<f.length;c++){var e=this.Je(b,f[c]);this.If(e,f[c]);this.Zd(f[c])}return b};var t=this.Ra;this.Ra=function(b,c){t(b,c);this.Zb&&1==this.gc&&(this.ya(["BillableMeasuredImpression"]),w?0==this.dataObj.$a&&this.ya(["GroupMMeasuredImpression"]):1!=this.dataObj.irtf&&this.ya(["GroupMMeasuredImpression"]))};this.Je=function(b,c){"undefined"===typeof c.settings.focus||c.settings.focus||(b.i=b.la);return b};
this.If=function(b,c){(!c.settings.measureType||"consecutive"==String(c.settings.measureType).toLowerCase())&&b.i<c.settings.adArea?c.buckets=0:b.i>=c.settings.adArea&&(!c.nb||1!=this.dataObj.irtf)&&(c.buckets+=this.ca.interval);c.N=b.N};this.Zd=function(b){b.nf||b.nb&&1==this.dataObj.irtf||!(this.Td(b)||b===this.Lc&&b.settings&&!b.settings.doNotReportViewedOnLargeAd&&b.N)||(this.R.T(this.c.ea(b.eventId),b.eventId),b.Qa&&this.ya(b.Qa),b.nf=!0)};this.Td=function(b){return b.buckets>=b.settings.duration?
!0:!1}}
function dv_InViewService(b){function e(){null===h.interval&&(h.interval=setInterval(h.Ae(),h.ca.interval))}function f(){if(!1===h.md){h.md=!0;try{h.b.La.remove("load",arguments.callee,!1,element)}catch(a){}h.Fb();h.b.a("s41");h.va=new la(h.de?h.de:h.window,h.f,h.S,h.L,h.O,h.c.ac,h.dvObj,h.impressionId);h.b.a("s42");h.Nd();h.start()}}function n(a,b){h.b.La.add("click",function(){h.Ub(!0);$dv.registerEventCall(h.impressionId,"ad"==b?{dvp_csad:1}:{dvp_csifr:1});h.b.La.remove("click",arguments.callee,!1,
a)},!1,a,!1)}var h=this;this.od=10;this.Xb=b.serverSettings&&b.serverSettings.jsVersion?b.serverSettings.jsVersion:"629";this.dvObj=b.dvObj||window.$dv;this.impressionId=b.impressionId||window.$uid;this._minor_version="0";this.b=new J;this.Ke=function(){for(var a=document.getElementsByTagName("script"),b=a.length,c,d=0;d<b;d++)if(c=a[d].src,/visit[.]js/.test(c))return c.substring(c.indexOf("?")+1)};this.md=!1;var r={serverProperties:{projected:"p",error:"perr",viewed:"pv",featurebit:"fb",viewedRate:"pvr"},
reportQueryString:{projected:"isprjct",measurems:"ismms",viewedms:"isiabvms",viewrate:"prjctvr",error:"prjcter"}},l=!1,w=!1;this.na=b.na||[];(this.Jf=b.prjct)&&this.na.push({serverData:b.prjct,projectionData:r,lf:!0,Kf:["MeasurementCapabilityDetected","ProjectedMeasured","IabView","ProjectedAssignedViewed"],ef:["MeasurementCapabilityDetected","ProjectedMeasured"]});r={serverProperties:{projected:"up",error:"uperr",viewed:"upv",viewedRate:"upvr"},reportQueryString:{projected:"isuprjct",measurems:"isumms",
viewedms:"isuiabvms",viewrate:"uprjctvr",error:"uprjcter"}};this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].uprjct&&this.na.push({serverData:this.dvObj.tags[this.impressionId].uprjct,projectionData:r});this.Fe=function(){var a="";this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].tagElement&&(a=this.dvObj.tags[this.impressionId].tagElement.src,a=a.substring(a.indexOf("?")+1));return a};this.$c=function(){return((new Date).getTime()+
""+Math.floor(1E6*Math.random())).substr(0,16)};this.$=function(a,b){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var c=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec("?"+b);return c=c?c[1]:null};this.He=function(){var a=this.$("uid",this.U);null==a?(a=this.$c(),this.U=this.U+"&uid="+a):""==a&&(a=this.$c(),this.U=this.U.replace("&uid=","&uid="+a));return a};this.vc=function(a,b,c,d){if(d&&d.insertBefore&&d.firstChild&&(a=this.window.document.createElement(a))){for(var e in b)a[e]=b[e];for(e in c)a.style[e]=
c[e];d.insertBefore(a,d.firstChild);return a}return null};this.ce=function(){var a=this.dvObj.Enums.TrafficScenario;try{if(window.top==window)return a.OnPage;if(window.top.document.domain==window.document.domain)return a.SameDomain}catch(b){}return a.CrossDomain};this.S=this.dvObj.CommonData.Scenario||this.ce();this.L={Y:this.dvObj.CommonData.BrowserId,wa:this.dvObj.CommonData.BrowserVersion};this.Z=this.dvObj.Enums.BrowserId;this.ba=this.dvObj.Enums.TrafficScenario;this.cb="default";this.dataObj=
b;this.window=b.tagWindow||parent.window||window;this.Hb=this.f=null;this.Ac=this.Ta=!1;this.sc=!0;this.interval=null;this.U=this.Ke();this.Oa=this.Fe();this.hf=b.serverSettings&&b.serverSettings.protocol&&0==b.serverSettings.protocol.indexOf("http")?b.serverSettings.protocol:window.location.protocol?window.location.protocol+"//":"http://";this.ca=window.le||this.window.le||{interval:100,Ca:{"default":{time:null,La:["beforeunload","unload"],Ad:9E5}}};this.qd={};var r="tps300.doubleverify.com",p=null;
try{this.dvObj.tags[this.impressionId].ServerPublicDns&&(r=this.dvObj.tags[this.impressionId].ServerPublicDns)}catch(a){}this.ja=window.dv_configServer||this.window.dv_configServer||{protocol:this.hf,port:"",domain:r,api:"event.jpg"};this.X=window.ke||this.window.ke||{interval:1E3,fa:6};r=b&&b.Cd?b.Cd:!1;b=b&&b.Dd?b.Dd:!1;!1!==r&&!1!==b&&(this.X.interval=r,this.X.fa=b,$dv.registerEventCall(this.impressionId,{Rf:this.X.interval,Sf:this.X.fa}));b=$dv&&$dv.CommonData&&(2==$dv.CommonData.deviceType||
3==$dv.CommonData.deviceType);this.ge={mb:12,ic:10,ab:30};this.O={Firefox:{aa:115},Chrome:{aa:89},Safari:{aa:38},Explorer:{aa:55},ff:500,Gf:0==b,ab:30};var t=!1,k=0,c=[5,10,15];window.devicePixelRatio&&(this.O.Firefox.aa=0);this.dataObj.spotXmode=this.dataObj.videoEnable||this.dataObj.detectVideoPlayer||this.dataObj.spotXmode;this.dvObj&&this.dvObj.tags&&this.dvObj.tags[this.impressionId]&&this.dvObj.tags[this.impressionId].spotXmode&&(this.dataObj.spotXmode=this.dvObj.tags[this.impressionId].spotXmode);
this.W=window.dv_configAdSize||this.window.dv_configAdSize||[{w:300,h:[100,250,268,600,618,850,1050]},{w:160,h:[600,800]},{w:120,h:[60,90,240,600,800]},{w:970,h:[66,90,250,30,415,550]},{w:728,h:[90,120]},{w:88,h:[31]},{w:700,h:[500]},{w:250,h:[60,250,300,360]},{w:180,h:[150,160,600]},{w:234,h:[60]},{w:468,h:[60]},{w:550,h:[480]},{w:125,h:[125]},{w:336,h:[280,600,850]},{w:745,h:[90]},{w:954,h:[60]},{w:184,h:[90]},{w:800,h:[600]},{w:320,h:[360]},{w:1280,h:[100]},{w:640,h:[480,90]},{w:270,h:[460,202]},
{w:613,h:[460]},{w:405,h:[303]},{w:950,h:[90]},{w:610,h:[100]},{w:272,h:[220]},{w:200,h:[200,446]},{w:220,h:[90]},{w:240,h:[133,400]},{w:960,h:[90]},{w:580,h:[400]},{w:750,h:[100,200,30]},{w:930,h:[180]},{w:980,h:[90,120]}];this.dataObj.spotXmode&&(this.W.push({w:320,h:[240]}),this.W.push({w:400,h:[300]}),this.W.push({w:450,h:[338]}),this.W.push({w:600,h:[800]}),this.W.push({w:640,h:[360]}),this.W.push({w:854,h:[480]}),this.W.push({w:500,h:[375]}));b&&(this.W.push({w:320,h:[50,100,480]}),this.W.push({w:300,
h:[50,31]}),this.W.push({w:120,h:[20]}),this.W.push({w:168,h:[28]}),this.W.push({w:216,h:[36]}),this.W.push({w:292,h:[30]}));this.cd=this.He();this.hc=!1;this.Nb=function(a,b){this.window.Rc||(this.window.Rc=[]);this.window.Rc.push({caller:a,Uf:b})};this.startTime=(new Date).getTime();this.Yd=4;this.Fc=0;this.oc=!0;this.logEvents={startMeasure:1,nonMeasurable:2,timeout:3,beforeunload:4,iabViewable:5,iabCustom:6,updateRTN:7,unload:8,projection:9,fraudMeasured:10,errorlevel1:16,Pf:17,interval:32};this.gc=
!1;this.Bd=function(){this.b.a("ie16");if(this.window.dv_logObject){var a=this.c.ue();this.window.dv_logObject[this.cd]=a}this.b.a("ie16e")};this.Ib=function(a){this.b.a("ie17");this.Ib=this.hc?function(a){this.c.vd(a);this.Bd()}:function(a){this.c.vd(a)};this.Ib(a)};this.zc=function(a,b){this.zc=this.hc?function(a,b){this.c.ud(a,b);this.Bd()}:function(a,b){this.c.ud(a,b)};this.zc(a,b)};this.Fb=function(){this.b.a("s4");this.f=this.ib.oe(this.X.fa);this.Hb=this.ib.Hb;!this.f&&this.S==this.ba.CrossDomain&&
this.b.xa(this.window)&&(this.X.fa=0);this.f?(this.tf(),this.c.kf(this.f),l||(n(this.f,"ad"),l=!0),w||this.S!=this.ba.CrossDomain&&this.S!=this.ba.SameDomain||(n(window.parent,"ifr"),w=!0),setTimeout(e,this.ib.Ya?10:50)):0<this.X.fa?(this.X.fa--,this.uf(),setTimeout(this.pe(),this.X.interval)):(this.S==this.ba.CrossDomain&&(this.b.nd(this.window,this.W)||this.b.xa(this.window))?(this.f=this.b.Ba(this.window),this.c.td()):this.S==this.ba.SameDomain&&this.b.nd(this.window,this.W)?(this.f=this.b.Ba(window.parent),
this.c.td(),this.fe()):this.X.fa=-1,setTimeout(e,10));this.b.a("s4e")};this.fe=function(){for(var a=this.window;a.parent!=a.top;)a=a.parent;this.b.a("ff26");for(var b=a.parent.document.getElementsByTagName("iframe"),c=b.length,d=0;d<c;d++)b[d].contentWindow==a&&(this.f=b[d],this.window=a.parent);this.b.a("ff26e")};this.uf=function(){this.dataObj.M&&this.dataObj.kb?this.c.yf():this.c.zf()};this.tf=function(){this.b.a("s9");this.Ta=!0;this.c.vf();this.b.a("s9e")};this.$d=function(){this.dataObj.Yb=
this.$("adsrv",this.U)||"";this.dataObj.M=this.$("btreg",this.U)||"";this.dataObj.pd=this.$("plcid",this.U)||"";"8"==this.dataObj.Yb&&""==this.dataObj.btreg&&(this.dataObj.M=this.dataObj.plcid);this.dataObj.kb=this.$("btadsrv",this.U)||"";this.dataObj.Hc=this.$("adid",this.U)||"";this.dataObj.Ye=this.$("isbtregex",this.Oa)||"";this.dataObj.ec=this.$("ctx",this.U)||"";this.dataObj.bc=this.$("cmp",this.U)||"";this.dataObj.$e=this.$("lomd",this.U)||"";this.dataObj.findclass=this.$("findclass",this.Oa)||
"";this.dataObj.displaynon=this.$("displaynon",this.Oa)||"";this.dataObj.Nc=this.$("bsdvview",this.Oa)||"";var a=this.$("bttag",this.Oa)||"";this.dataObj.lb=0<a.length?a.split("|"):[];a=this.$("btattb",this.Oa)||"";this.dataObj.Ja=0<a.length?a.split("|"):[]};this.bb=function(a){a=this.ya(a);return 0<a.length?"&tagServiceResult="+encodeURIComponent(a.join(",")):""};this.ya=function(a){if(!this.dvObj||!this.impressionId)return[];for(var b=[],c=0;c<a.length;c++){var d=this.dvObj.pubSub.publish(a[c],
this.impressionId)||null;null!=d&&b.push(d)}return b};this.Ne=function(a){1==a&&(this.c.Ff(),this.dvObj&&this.impressionId&&this.c.rc()&&(a=this.bb(["MeasurementCapabilityDetected","GeoMeasured"]),this.R.T(this.c.ea(this.logEvents.fraudMeasured)+a,this.logEvents.fraudMeasured)))};this.Me=function(a){var b="",c=a.serverData,d=a.projectionData;1==c[d.serverProperties.featurebit]&&(b=1==c[d.serverProperties.viewed]?this.bb(a.Kf):this.bb(a.ef));return b};this.Gd=function(){this.dataObj.serverSettings&&
this.dataObj.serverSettings.TKH&&(this.U+="&TKH="+this.dataObj.serverSettings.TKH)};this.je=function(){Array.prototype.indexOf=function(a){if(null==this)throw new TypeError;var b=Object(this),c=b.length>>>0;if(0===c)return-1;var d=0;1<arguments.length&&(d=Number(arguments[1]),d!=d?d=0:0!=d&&Infinity!=d&&-Infinity!=d&&(d=(0<d||-1)*Math.floor(Math.abs(d))));if(d>=c)return-1;for(d=0<=d?d:Math.max(c-Math.abs(d),0);d<c;d++)if(d in b&&b[d]===a)return d;return-1}};this.inViewManager=function(){try{Array.prototype.indexOf||
this.je();var a=this.ja.protocol+this.ja.domain+this.ja.port+"/"+this.ja.api;this.Gd();this.c=new aa(this.Xb,this.U,a,this.ge,this.dataObj);var b=new ba(this.window,this.cd);this.dataObj.isReportingDisabled?(X.prototype=b,this.R=new X):this.R=b;this.dataObj.isRTNsDisabled&&(this.ya=function(){return[]});this.hc=this.window.dv_logObject?!0:!1;this.Af();if(!this.c.ac()&&(this.Le(),void 0!=this.dataObj.prjct&&1==this.dataObj.prjct.p&&1==this.dataObj.prjct.fb))return;this.Ne(this.dataObj.irtf);this.$d();
this.ib=new ma(this.dataObj,this.W,this.window,this.c,this.S);var c=window.parent;"589953"==this.dataObj.ec&&"587351"==this.dataObj.bc||"589953"==this.dataObj.ec&&"616389"==this.dataObj.bc||"polite"==this.dataObj.$e?(setTimeout(f,15E3),this.b.La.add("load",function(){setTimeout(f,1E3)},!1,c,!1)):f()}catch(d){var e=this;this.Sa(function(){e.Nb("inViewManager",d);e.c.wc("inViewManager",d);e.R.T(e.c.ea(e.logEvents.errorlevel1),e.logEvents.errorlevel1)},"inViewManager",d)}};this.Le=function(){for(var a=
"",b=0;b<this.na.length;b++){var c=this.na[b];this.c.Df(c.serverData,c.projectionData);!0===c.lf&&(a+=this.Me(c))}0<this.na.length&&this.R.T(this.c.ea(this.logEvents.projection)+a,this.logEvents.projection)};this.gb=function(a){this.b.a("ie20");-6!=a.i&&(-3==a.i||-5!=a.i&&0>a.i&&-1==this.X.fa)&&(this.Cc(),this.gb=function(){})};this.Cc=function(){this.R.T(this.c.ea(this.logEvents.nonMeasurable),this.logEvents.nonMeasurable);this.ya(["ImpressionNotMeasured"]);this.Cc=function(){}};this.Ra=function(a,
b){a.b.a("ie21");if(0<=b.i||-5==b.i&&-1>=a.X.fa){if(a.dvObj&&a.impressionId&&0==a.c.rc()){a.b.a("ie23");var c=a.bb(["MeasurementCapabilityDetected","GeoMeasured"]);a.b.a("ie24");var d=a.c.ea(a.logEvents.startMeasure);a.R.T(d+c,a.logEvents.startMeasure)}else a.R.T(a.c.ea(a.logEvents.startMeasure),a.logEvents.startMeasure);a.gc=!0;a.Ra=function(){};a.gb=function(){}}a.b.a("ie22")};this.Ub=function(a){this.b.a("ie25");if(this.c.Vc()||a&&!0===a)this.b.a("ie27"),this.dvObj&&this.impressionId&&0==this.c.rc()?
(this.b.a("ie28"),a=this.bb(["IabView","GeoViewed"]),this.b.a("ie29"),this.R.T(this.c.ea(this.logEvents.iabViewable)+a,this.logEvents.iabViewable)):this.R.T(this.c.ea(this.logEvents.iabViewable),this.logEvents.iabViewable),t=!0,this.Ub=function(){};this.b.a("ie26")};this.acumulateViewableTime=function(a){if(t&&this.c.Vc())for(k+=a,a=0;a<c.length;a++)null!=c[a]&&k>=1E3*c[a]&&(this.ya(["viewd"+c[a]+"sec"]),c[a]=null)};var g="hidden",d=0;this.hasFocus=function(){vis=["hidden","webkitHidden","mozHidden",
"msHidden","oHidden"];for(hiddenProp in vis)if(vis[hiddenProp]in document){g=vis[hiddenProp];break}var a=1==this.b.Va("fcs"),b=!1;try{this.b.Xa(this.window),b=!0}catch(c){}var e=!1;try{this.b.Xa(this.window.top),e=!0}catch(c){}var f=null,f=a&&b&&this.L.Y==this.Z.IE?function(){var a=h.b.Xa(h.window);h.S==h.ba.OnPage&&(a=a&&h.sc);return a}:a&&e?function(){var a=!0,a=h.b.Xa(h.window.top);h.S==h.ba.OnPage&&(a=a&&h.sc);return a}:"undefined"!==typeof document[g]?function(){return!h.window.document[g]}:
e?function(){return h.b.Xa(h.window.top)}:function(){return!0};this.hasFocus=function(){try{return f()}catch(a){d++,5<=d&&(this.hasFocus=function(){return!0})}return!0};return this.hasFocus()};this.mc=function(a){var b=a.va.ye();a.b.a("ie12");null==this.f||-3==b.i||a.hasFocus()||(b.i=0);a.b.a("ie13");return p=b};this.Qb=function(a){a.b.a("ie1");var b=a.f?a.f.ub||a.window:a.window;a.va.f=a.f;a.va.window=b;a.b.a("ie2");b=a.mc(a);a.Ta&&(-1==b.i||-2==b.i)&&-1<=a.X.fa&&(a.sd(a),a.Fb());a.b.a("ie3");-5==
b.i&&(a.X.fa--,a.c.wd(),a.Pa||(a.Pa=function(b){b=a.va.xb(b);a.c.eb(b)}));a.b.a("ie4");a.Pa&&0<b.i&&(a.Pa(b),a.Pa=null);a.b.a("ie5");if(a.Ta&&!a.Ac){a.Ac=!0;var c=a.va.xb(b);a.c.eb(c)}-5==b.i&&-1<=a.X.fa&&(a.sd(a),a.Fb(),b=a.mc(a),-5==b.i&&0<a.X.fa&&a.c.qf());a.b.a("ie6");a.zc(b,a.ca.interval);a.b.a("ie7");a.Ib(b);a.b.a("ie8");a.c.yd(b.ha);a.gb(b);a.b.a("ie9");a.Ra(a,b);a.b.a("ie10");a.Ub();a.b.a("ie11");a.acumulateViewableTime(a.ca.interval);a.b.a("ie12");return b};this.sd=function(a){a.Ta=!1;a.f=
null;a.ib.pf();a.va.Oe()};this.Ae=function(){this.b.a("s26");var a=this;return function(){try{a.Qb(a)}catch(b){a.Sa(function(){a.Fc<a.Yd&&(a.Fc++,a.Nb("getIntervalCallback",b),a.c.wc("getIntervalCallback",b),a.R.T(a.c.ea(a.logEvents.errorlevel1),a.logEvents.errorlevel1))},"getIntervalCallback",b)}}};this.Zc=function(a){var b=this;return function(){b.Sa(function(){b.L.Y==b.Z.IE?b.R.T(b.c.ea(b.logEvents[a]),b.logEvents[a]):b.R.Jb(b.c.ea(b.logEvents[a]),b.logEvents[a])},"getReportEventCallback")}};this.pe=
function(){var a=this;return function(){a.Sa(function(){a.Fb();a.f||a.c.Gb()},"getAdLocateCallback")}};this.Wa=function(){var a=this;return function(b){try{b||(b=a.window.event),a.sc="blur"==b.type||"focusout"==b.type?!1:!0}catch(c){try{b="",a.b?b=a.b.tb():a.b&&(b=a.b.tb()),a.R.T(a.ja.protocol+a.ja.domain+a.ja.port+"/"+a.ja.api+"?"+a.U+"&ctime="+(new Date).getTime()+"&evid="+a.logEvents.errorlevel1+"&jsver="+a.Xb+b+"&napr=getFocBluEventCallback: "+c.message,a.logEvents.errorlevel1)}catch(d){}}}};
this.Md=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this;this.dvObj.tags[this.impressionId].getViewabilityData=function(){try{for(var b=a.c.ve().slice(0),c=0;c<b.length;c++)void 0===b[c]||null===b[c]?b[c]=0:isNaN(b[c])||(b[c]/=1E3);var d={};d.bucket_0=b[0];d.bucket_1_9=b[1];d.bucket_100=b[11];for(c=2;10>=c;c++)d["bucket_"+(10*(c-1)).toString()+"_"+(10*c-1).toString()]=b[c];return{buckets:d,isAdMeasureable:a.gc,totalPageTime:(a.c.qb()-a.c.Ee())/1E3,notApplicableTime:a.c.Yc()/
1E3}}catch(e){return{}}}}}catch(b){}};this.Nd=function(){try{if(this.dvObj&&this.impressionId&&this.dvObj.tags[this.impressionId]){var a=this.dvObj.tags[this.impressionId];a.VA||(a.VA={});a.VA.getVisibilityResult=function(){var a={};a.perc=p.i;0<=p.i&&p.I&&p.I.j&&(a.adWidth=p.I.j.o,a.adHeight=p.I.j.m);return a};a.VA.getAdElem=function(){return h.f}}}catch(b){}};this.Md();this.start=function(){this.b.a("s35");this.gf(this);var a;this.ca&&this.ca.Ca&&this.ca.Ca[this.cb]&&(a=this.ca.Ca[this.cb].La);
if(a)for(var b=a.length,c=0;c<b;c++)this.qd[a[c]]=this.Zc(a[c]),this.Ia(this.window,a[c],this.qd[a[c]]);this.Cf();this.ca&&this.ca.Ca&&this.ca.Ca[this.cb]&&this.ca.Ca[this.cb].Ad&&setTimeout(this.mf(),this.ca.Ca[this.cb].Ad)};this.mf=function(){var a=this;return function(){a.Zc("timeout")();clearInterval(a.interval);a.R.Jb=function(){};a.R.T=function(){}}};this.gf=function(a){try{var b=a.mc(a);-5==b.i&&(this.c.wd(),this.Pa||(this.Pa=function(b){b=a.va.xb(b);a.c.eb(b)}));if(a.Ta)if(this.Ac=!0,-5!=
b.i){var c=a.va.xb(b);a.c.eb(c)}else a.c.eb("true");a.c.yd(b.ha);var d=a.va.re(b,a.c.Yc());a.c.xf(d);a.c.xd(b.i);a.Ib(b);a.gb(b);a.Ra(a,b)}catch(e){a.Sa(function(){a.Nb("onStartReport",e);a.c.wc("onStartReport",e);a.R.T(a.c.ea(a.logEvents.errorlevel1),a.logEvents.errorlevel1)},"onStartReport",e)}};this.Cf=function(){this.Ia(this.window,"blur",this.Wa());this.Ia(this.window,"focus",this.Wa());this.Ia(this.window.document,"click",this.Wa());this.Ia(this.window.document,"mousedown",this.Wa());this.Ia(this.window.document,
"mouseup",this.Wa())};this.Ia=function(){function a(b,c,d){a=b.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:b.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a(b,c,d)}return function(b,c,d){a(b,c,d)}}();this.stop=function(){};this.Af=function(){this.b.a("ff24");this.S==this.ba.CrossDomain?this.b.xa(this.window)||this.b.qc(this.window)||this.b.yb()||this.b.zb(this.S,this.L,this.dvObj)||(this.L.Y!=this.Z.Firefox&&this.L.Y!=this.Z.IE?this.c.Bf():this.L.Y==
this.Z.Firefox&&"undefined"===typeof this.window.mozInnerScreenX&&this.c.xc()):window.document.body.getBoundingClientRect||this.c.xc();this.oc=this.c.ac();this.b.a("ff24e")};this.Sa=function(a,b,c){try{a()}catch(d){try{if(0<this.od){this.od--;var e=this.b.tb(),f=this.b.Wc(b||"unknown caller",c||d);this.R.T(this.ja.protocol+this.ja.domain+this.ja.port+"/"+this.ja.api+"?"+this.U+"&ctime="+(new Date).getTime()+"&evid="+this.logEvents.errorlevel1+"&jsver="+this.Xb+e+"&napr="+f,this.logEvents.errorlevel1)}}catch(g){}}};
return this}
try{window.dv_InViewService=dv_InViewService;dv_InViewService.prototype.inViewManager=dv_InViewService.prototype.inViewManager;var ViewAssureBootstrapper=function(b){$dv.tags[$uid].gmmod||$dv.tags[$uid].cvmSettings||$dv.tags[$uid].billable||b.cvmSettings||b.billable?(new dv_CustomClientViewAssureService(b)).inViewManager():(new dv_InViewService(b)).inViewManager()};if("function"===typeof window.IVCallback)IVCallback(ViewAssureBootstrapper);else for(var na=[window.$dvbs,window.$dvbsr],Z=0;Z<na.length;Z++){var dvObj=
na[Z];if(dvObj&&"object"===typeof dvObj&&"function"===typeof dvObj.getTagObjectByService){var tagObject=dvObj.getTagObjectByService("avs629");if(tagObject){var serviceParams=tagObject.services.avs629;serviceParams&&serviceParams.params&&ViewAssureBootstrapper(serviceParams.params)}}}}catch(b){};
